### PR TITLE
Fix: race condition in nested components

### PR DESCRIPTION
**Pull request by helio3197**
Fix race condition in nested components. Skip `Alpine.init` call on elements with an ancestor with `x-ignore`.
#39

### CODE REVIEW

**Comment by allensquare** [comment]
This logic makes sense to me. I did some testing around this and seems to work well with nesting, also appears to fix my use case, thank you!

@Accudio thoughts on this solution? It appears inline with what you were suggesting.

**Comment by Accudio** [comment]
@helio3197 @allensquare This is pretty much like I was thinking, thank you for the contribution! I've got a busy week but will review and test this at the weekend.

**Comment by howdu** [comment]
This fixed an issue I was having but nested components, but are you aware it broke Filament's modal?
https://github.com/filamentphp/filament/releases/tag/v3.2.37

**Comment by Accudio** [comment]
Thanks for flagging @howdu. @danharrin would you or another member of the Filament team be able to file an issue with your modal implementation and a test case and I can take a look into this?

I believe the behaviour in 1.2.2 is the most correct, reliable and consistent and am surprised it caused a breaking change, but there may be something I missed or it's implementation-based.

**Comment by danharrin** [comment]
Hi @Accudio, I would like to, but currently I don't really have time to dig into it, and locking the dependency was the easiest way for us to move forward.

@howdu if you're looking to use the functionality of this release, you can make a reproduction for us if you want, just use any Alpine form component like Select in a modal.

**Pull request merged**
